on:
  push:
    paths-ignore: # skip firmware rebuild for docs and rendered keymap diagrams
      - "keymap-drawer/**"
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
